---
# tasks file for mysql
- name: Create mysql database
  become: true
  mysql_db: 
    name={{ wp_mysql_db }} 
    state=present 
    # These are no longer required as we set /root/.my.cnf
    # login_user=root 
    # login_password=""

- name: Create mysql user
  # @todo In Ubuntu 16, this doesn't work
  # We have to run something like
  # `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test';`
  become: true
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL
    # These are no longer required as we set /root/.my.cnf
    # login_user=root 
    # login_password="" 

