---
# tasks file for wordpress
- name: Download WordPress  
  become: true
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no 

- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no 
  become: true

- name: Update default Apache site
  become: true
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: true

 
- name: Cambio definitivo por la variable 1
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "'database_name_here'"
    replace: "{{ wp_mysql_db }}"
  become: true

- name: Cambio definitivo por la variable 2 
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "'username_here'"
    replace: "{{ wp_mysql_user }}"
  become: true

- name: Cambio definitivo por la variable 3
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "'password_here'"
    replace: "{{ wp_mysql_password }}"
  become: true
